### ISSUE TITLE
generate an initial master JSON file

### ISSUE THREAD

**Issue by kroylar** [kroylar/lofi-server#1]
We will construct the master JSON file that contains the full current status.  This will be constructed on the fly as messages come in. New messages will automatically add new entries. Entries will also be automatically added initially as status UNKNOWN based on the mapping.conf file. They will be updated as their respective messages come in.
- read the mapping.conf file and populate an initial master json with status unknown for all the locations in the mapping.conf file
- receive messages from the LoFi receiver (a separate program) probably over a socket, ethernet, or UART
- check the master json file to see if that entry is already there
  - only need to check the node_id
- if the entry is there append a history item to it else create it. This allows us to add new LoFi's on the fly and have them automatically and immediately included in the security report.
  - create the entry by matching the node_id to the location number using mapping.conf
  - add all the location details in layout.conf
  - add an entry to the history field

We'll also send a partial json (the entry with only this, the latest status change) to all the connected clients.

**Comment by kroylar** [comment]
The data from the LoFi receiver will include:
- **node_id** - This is the number that uniquely identifies all the LoFi's
- **state** - OPEN or CLOSED (unknown will be generated by our server after a timout with no received messages)
- **voltage** - optional field. Will probably be sent once a day or less

**Comment by kroylar** [comment]
Let's have the server build the master JSON initially from the layout.conf file and the mapping.conf.

For those locations that have a mapping to a LoFi node_id, we'll just mark the state as "unknown".

For those locations that do not have a mapping, we'll mark both the state and the LoFi node_id as "unknown".

**Comment by kroylar** [comment]
A lot of this overlaps with #2. Let's just generate the initial file in this ticket.

**Comment by 0not** [comment]
Is it worth allowing non-integer IDs in mapping.conf? (I'm talking about how it currently lists 5a and 5b).

**Comment by kroylar** [comment]
I thought about that too. Its not. Let's add another optional field to tell us what switch position is used. The default is 0, unless otherwise specified.

**Comment by kroylar** [comment]
Also use a sqlite database to keep the history of changes. The initial creation of the json will include the history of each location.

**Comment by kroylar** [comment]
Done in fcfc85ad3acb14968ff02c6c099c45618801f336.
