### ISSUE TITLE
highlight the house locations on the layout image with the current security state

### ISSUE THREAD

**Issue by kroylar** [kroylar/lofi-server#4]
@0not can you explain how this will be done?

**Comment by 0not** [comment]
@kroylar I'm going to manually assign each door or window SVG element a unique ID, as we decide for layout.conf (or mapping.conf, whichever it is). That ID will be associated with a lofi, and the lofi status will affect the color of the SVG element.  Make sense?

**Comment by kroylar** [comment]
http://www.w3schools.com/svg/svg_reference.asp

Awesome! I didn't realize how much control one had over SVG's in a browser.

**Comment by kroylar** [comment]
Done in fcfc85ad3acb14968ff02c6c099c45618801f336.
